# Docker Compose Configuration for MySQL Database

version: '3.8'

services:
  food-db:  
    image: mysql:8  
    ports:
      - 3306:3306  
    environment:
      MYSQL_ROOT_PASSWORD: 123  
      MYSQL_DATABASE: foodApp 
    networks:
      - yCode 

networks:
  yCode:  
